import "./globals.css";
import "./styles.scss";
import { Inter } from "next/font/google";
import Header from "./components/Header";
const inter = Inter({ subsets: ["latin"] });
import Providers from "./Provider";
import { ClerkProvider } from "@clerk/nextjs";
import { getUserById, updateUserInfo } from "@/lib/users";
import { currentUser } from "@clerk/nextjs";
import { getProductById } from "@/lib/products";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const sessionUser = await currentUser();
  let count;
  let productsData;
  const products: Array<string> = [];
  if (sessionUser) {
    const { user } = await getUserById(sessionUser?.id);
    count = user?.Cart.length;
    user?.Cart.map((item: any) => {
      products.push(item?.id);
    });
    productsData = (await getProductById(products)).product;
    // productsData?.slice(-3);
    // console.log(productsData);
    if ((user?.Name == "" || user?.Email == "" || user?.Image == "") && user) {
      await updateUserInfo(
        sessionUser.id,
        sessionUser.firstName || "User" + sessionUser.lastName || "",
        sessionUser.emailAddresses[0].emailAddress,
        sessionUser.profileImageUrl
      );
    }
  }
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <Providers>
            <Header
              products={productsData?.slice(0, 3) || []}
              count={count || 0}
            />
            {children}
          </Providers>
        </body>
      </html>
    </ClerkProvider>
  );
}
