import "./globals.css";
import "./styles.scss";
import { Inter } from "next/font/google";
import Provider from "./components/Provider";
const inter = Inter({ subsets: ["latin"] });
import Providers from "./Providers";
import NavLayout from "./components/NavLayout";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <Providers>
            {/* @ts-ignore */}
            <NavLayout>
              <div className="sm:ml-[200px]  p-4 pb-0">{children}</div>
            </NavLayout>
          </Providers>
        </Provider>
      </body>
    </html>
  );
}
