import "./globals.css";
import "./styles.scss";
import { Inter } from "next/font/google";
import Provider from "./components/Provider";
import Theme from "./components/Theme";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Theme>
          <Provider>{children}</Provider>
        </Theme>
      </body>
    </html>
  );
}
