import "./globals.css";
import "./styles.scss";
import { Inter } from "next/font/google";
import Provider from "./components/Provider";
const inter = Inter({ subsets: ["latin"] });
import Providers from "./Providers";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Provider>
        <body className={inter.className}>
          <Providers> {children} </Providers>
        </body>
      </Provider>
    </html>
  );
}
