export const colors = [
  { value: 1, label: "Red" },
  { value: 2, label: "Green" },
  { value: 3, label: "Black" },
  { value: 4, label: "Yellow" },
  { value: 5, label: "White" },
  { value: 6, label: "Blue" },
  { value: 7, label: "Violet" },
  { value: 8, label: "Indigo" },
  { value: 9, label: "Purple" },
  { value: 10, label: "Orange" },
  { value: 11, label: "Brown" },
  { value: 12, label: "Pink" },
  { value: 13, label: "Silver" },
  { value: 14, label: "Gray" },
  { value: 15, label: "Beige" },
  { value: 16, label: "Turquoise" },
  { value: 17, label: "RGB" },
  { value: 18, label: "Transparent" },
];
